### ISSUE TITLE
Subclassing SKAction

### ISSUE THREAD

**Issue by Wh1rlw1nd** [thirteen23/RainCat#1]
I was looking through your code and noticed that you have subclassed an `SKAction`. This is from the [docs](https://developer.apple.com/reference/spritekit/skaction):

> You never subclass SKAction directly. Instead, create actions that call methods on arbitrary objects or execute blocks of code

You did `ColorAction:SKAction` , so you could consider changing that.

Ps. Tutorial and the game look nice! Looking forward to the iPhone version of Rain Cat :p :)

**Comment by marcJV** [comment]
Fixed in the LCD game branch, will be in master soon!
